# Generated by Django 6.0.4 on 2026-05-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
