# Generated by Django 6.0.4 on 2026-05-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectmark',
            old_name='mark',
            new_name='marks',
        ),
        migrations.AddField(
            model_name='subject',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
